#cloud-config

write_files:
  - path: /etc/systemd/system/culpa.service
    content: |
      [Unit]
      Description=Flask Backend Server for CULPA
      After=network.target

      [Service]
      Type=simple
      User=ubuntu
      Environment=FLASK_ENV=production
      WorkingDirectory=/data
      ExecStartPre=/usr/bin/python3.7 -m pipenv install
      ExecStart=/usr/bin/python3.7 -m pipenv run gunicorn -b 127.0.0.1:8000 -w 4 "api.app:create_app()"
      Restart=always

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/culpa-reloader.service
    content: |
      [Unit]
      Description=CULPA restarter
      After=network.target
      StartLimitIntervalSec=10
      StartLimitBurst=5

      [Service]
      Type=oneshot
      ExecStart=/bin/systemctl restart culpa.service

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/culpa-reloader.path
    content: |
      [Path]
      Unit=culpa-reloader.service
      PathChanged=/data/api

      [Install]
      WantedBy=multi-user.target

  - path: /run/tmp/default
    content: |
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /data/build;

        index index.html;

        server_name _;

        location / {
          try_files $uri $uri/ /index.html;
        }

        location /static {
          expires 1y;
          add_header Cache-Control "public";
        }

        location /api {
          include proxy_params;
          proxy_pass http://127.0.0.1:5000;
        }
      }

  - path: /data/build/index.html
    content: |
      <html><body>hi this is working</body></html>

packages:
  - python3.7
  - python3-pip
  - nginx

runcmd:
  - sudo chown -R ubuntu:ubuntu /data
  - python3.7 -m pip install pipenv
  - sudo cp /run/tmp/default /etc/nginx/sites-available/default
  - sudo systemctl stop apache2
  - sudo systemctl start nginx
  - sudo systemctl start culpa.service culpa-reloader.service culpa-reloader.path
