# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Frontend CI

on: [push, pull_request]

jobs:
  react-frontend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Lint with eslint
        run: yarn lint-js
      - name: Test
        run: yarn test-frontend
